<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="chips" nsURI="platform:/resource/Chips2BIP/Chips1.0.ecore" nsPrefix="chips">
  <eClassifiers xsi:type="ecore:EClass" name="program">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" upperBound="-1"
        eType="#//definition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="system_description" upperBound="-1"
        eType="#//instructions/description_instruction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="unnamedProgram" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="int" instanceTypeName="intvalue"/>
  <eClassifiers xsi:type="ecore:EDataType" name="float" instanceTypeName="floatvalue"/>
  <eClassifiers xsi:type="ecore:EDataType" name="bool" instanceTypeName="boolvalue"/>
  <eClassifiers xsi:type="ecore:EClass" name="input" abstract="true">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="output" abstract="true">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="definition" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="instance" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="instruction" abstract="true" interface="true"/>
  <eSubpackages name="variables" nsURI="platform:/resource/Chips2BIP/Chips1.0.ecore/variables"
      nsPrefix="chips.variables">
    <eClassifiers xsi:type="ecore:EClass" name="variable" abstract="true">
      <eTypeParameters name="T"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eGenericSuperTypes eClassifier="#//input">
        <eTypeArguments eTypeParameter="#//variables/variable/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="int_var">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" containment="true">
        <eGenericType eClassifier="#//expressions/expression">
          <eTypeArguments eClassifier="#//int"/>
        </eGenericType>
      </eStructuralFeatures>
      <eGenericSuperTypes eClassifier="#//variables/variable">
        <eTypeArguments eClassifier="#//int"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="float_var">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" containment="true">
        <eGenericType eClassifier="#//expressions/expression">
          <eTypeArguments eClassifier="#//float"/>
        </eGenericType>
      </eStructuralFeatures>
      <eGenericSuperTypes eClassifier="#//variables/variable">
        <eTypeArguments eClassifier="#//float"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="bool_var">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" containment="true">
        <eGenericType eClassifier="#//expressions/expression">
          <eTypeArguments eClassifier="#//bool"/>
        </eGenericType>
      </eStructuralFeatures>
      <eGenericSuperTypes eClassifier="#//variables/variable">
        <eTypeArguments eClassifier="#//bool"/>
      </eGenericSuperTypes>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="expressions" nsURI="platform:/resource/Chips2BIP/Chips1.0.ecore/expressions"
      nsPrefix="chips.expressions">
    <eClassifiers xsi:type="ecore:EClass" name="expression" abstract="true">
      <eTypeParameters name="T"/>
      <eGenericSuperTypes eClassifier="#//output">
        <eTypeArguments eTypeParameter="#//expressions/expression/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="direct_int">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eGenericSuperTypes eClassifier="#//expressions/expression">
        <eTypeArguments eClassifier="#//int"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="direct_float">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eGenericSuperTypes eClassifier="#//expressions/expression">
        <eTypeArguments eClassifier="#//float"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="direct_bool">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eGenericSuperTypes eClassifier="#//expressions/expression">
        <eTypeArguments eClassifier="#//bool"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="binary_expression">
      <eTypeParameters name="LTYPE"/>
      <eTypeParameters name="RTYPE"/>
      <eTypeParameters name="T"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1"
          containment="true">
        <eGenericType eClassifier="#//expressions/expression">
          <eTypeArguments eTypeParameter="#//expressions/binary_expression/LTYPE"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="+"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1"
          containment="true">
        <eGenericType eClassifier="#//expressions/expression">
          <eTypeArguments eTypeParameter="#//expressions/binary_expression/RTYPE"/>
        </eGenericType>
      </eStructuralFeatures>
      <eGenericSuperTypes eClassifier="#//expressions/expression">
        <eTypeArguments eTypeParameter="#//expressions/binary_expression/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="variable_expression" abstract="true">
      <eTypeParameters name="T"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1">
        <eGenericType eClassifier="#//input">
          <eTypeArguments eTypeParameter="#//expressions/variable_expression/T"/>
        </eGenericType>
      </eStructuralFeatures>
      <eGenericSuperTypes eClassifier="#//expressions/expression">
        <eTypeArguments eTypeParameter="#//expressions/variable_expression/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="unary_expression">
      <eTypeParameters name="U"/>
      <eTypeParameters name="T"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sub_expression" lowerBound="1"
          containment="true">
        <eGenericType eClassifier="#//expressions/expression">
          <eTypeArguments eTypeParameter="#//expressions/unary_expression/U"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="+"/>
      <eGenericSuperTypes eClassifier="#//expressions/expression">
        <eTypeArguments eTypeParameter="#//expressions/unary_expression/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="purecall_expression">
      <eTypeParameters name="T"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arg_expressions" upperBound="-1"
          containment="true">
        <eGenericType eClassifier="#//expressions/expression">
          <eTypeArguments/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pure_function" lowerBound="1"
          eType="#//definables/pure_def"/>
      <eGenericSuperTypes eClassifier="#//expressions/expression">
        <eTypeArguments eTypeParameter="#//expressions/purecall_expression/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="object_output">
      <eTypeParameters name="T"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="src_object" lowerBound="1"
          eType="#//instances/object_instance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="out_index">
        <eGenericType eClassifier="#//expressions/expression">
          <eTypeArguments eClassifier="#//int"/>
        </eGenericType>
      </eStructuralFeatures>
      <eGenericSuperTypes eClassifier="#//output">
        <eTypeArguments eTypeParameter="#//expressions/object_output/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="variable_expression_int">
      <eGenericSuperTypes eClassifier="#//expressions/variable_expression">
        <eTypeArguments eClassifier="#//int"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="variable_expression_float">
      <eGenericSuperTypes eClassifier="#//expressions/variable_expression">
        <eTypeArguments eClassifier="#//float"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="variable_expression_bool">
      <eGenericSuperTypes eClassifier="#//expressions/variable_expression">
        <eTypeArguments eClassifier="#//bool"/>
      </eGenericSuperTypes>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="instructions" nsURI="platform:/resource/Chips2BIP/Chips1.0.ecore/instructions"
      nsPrefix="chips.instructions">
    <eClassifiers xsi:type="ecore:EClass" name="process_instruction" abstract="true"
        eSuperTypes="#//instruction"/>
    <eClassifiers xsi:type="ecore:EClass" name="description_instruction" abstract="true"
        eSuperTypes="#//instruction"/>
    <eSubpackages name="process" nsURI="platform:/resource/Chips2BIP/Chips1.0.ecore/instructions/process"
        nsPrefix="chips.instructions.process">
      <eClassifiers xsi:type="ecore:EClass" name="assignment" eSuperTypes="#//instructions/process_instruction">
        <eTypeParameters name="T"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1">
          <eGenericType eClassifier="#//input">
            <eTypeArguments eTypeParameter="#//instructions/process/assignment/T"/>
          </eGenericType>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
            containment="true">
          <eGenericType eClassifier="#//expressions/expression">
            <eTypeArguments eTypeParameter="#//instructions/process/assignment/T"/>
          </eGenericType>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="variable_declaration" abstract="true"
          eSuperTypes="#//instructions/process_instruction">
        <eTypeParameters name="T"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
            containment="true">
          <eGenericType eClassifier="#//variables/variable">
            <eTypeArguments eTypeParameter="#//instructions/process/variable_declaration/T"/>
          </eGenericType>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="int_var_declaration">
        <eGenericSuperTypes eClassifier="#//instructions/process/variable_declaration">
          <eTypeArguments eClassifier="#//int"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="float_var_declaration">
        <eGenericSuperTypes eClassifier="#//instructions/process/variable_declaration">
          <eTypeArguments eClassifier="#//float"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="bool_var_declaration">
        <eGenericSuperTypes eClassifier="#//instructions/process/variable_declaration">
          <eTypeArguments eClassifier="#//bool"/>
        </eGenericSuperTypes>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="description" nsURI="platform:/resource/Chips2BIP/Chips1.0.ecore/instructions/description"
        nsPrefix="chips.instructions.description">
      <eClassifiers xsi:type="ecore:EClass" name="plug_inputs" eSuperTypes="#//instructions/description_instruction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="receiving_block" lowerBound="1"
            eType="#//instances/object_instance"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" lowerBound="1"
            upperBound="-1">
          <eGenericType eClassifier="#//output">
            <eTypeArguments/>
          </eGenericType>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="link" eSuperTypes="#//instructions/description_instruction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="support_object" lowerBound="1"
            eType="#//instances/object_instance"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="supported_logical_function"
            eType="#//instances/logical"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="location" eSuperTypes="#//instructions/description_instruction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate" lowerBound="1"
            upperBound="-1">
          <eGenericType eClassifier="#//expressions/expression">
            <eTypeArguments eClassifier="#//float"/>
          </eGenericType>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="located_block" lowerBound="1"
            eType="#//instances/physical"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="object_declaration" eSuperTypes="#//instructions/description_instruction">
        <eTypeParameters name="OTYPE">
          <eBounds eClassifier="#//instances/object_instance"/>
        </eTypeParameters>
        <eStructuralFeatures xsi:type="ecore:EReference" name="definition_ref" lowerBound="1"
            eType="#//definables/object_def"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="instance" lowerBound="1"
            containment="true">
          <eGenericType eTypeParameter="#//instructions/description/object_declaration/OTYPE"/>
        </eStructuralFeatures>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="instances" nsURI="platform:/resource/Chips2BIP/Chips1.0.ecore/instances"
      nsPrefix="chips.instances">
    <eClassifiers xsi:type="ecore:EClass" name="program_var" eSuperTypes="#//instance"/>
    <eClassifiers xsi:type="ecore:EClass" name="object_instance" abstract="true" eSuperTypes="#//instance"/>
    <eClassifiers xsi:type="ecore:EClass" name="physical" eSuperTypes="#//instances/object_instance"/>
    <eClassifiers xsi:type="ecore:EClass" name="logical" eSuperTypes="#//instances/object_instance"/>
  </eSubpackages>
  <eSubpackages name="definables" nsURI="platform:/resource/Chips2BIP/Chips1.0.ecore/definables"
      nsPrefix="chips.definables">
    <eClassifiers xsi:type="ecore:EClass" name="import_def" eSuperTypes="#//definition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="src_file" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="as_name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="function_def" abstract="true" eSuperTypes="#//definition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          containment="true">
        <eGenericType eClassifier="#//parameters/parameter">
          <eTypeArguments/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="output_flow" lowerBound="1"
          upperBound="-1" containment="true">
        <eGenericType eClassifier="#//expressions/expression">
          <eTypeArguments/>
        </eGenericType>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="pure_def" eSuperTypes="#//definables/function_def"/>
    <eClassifiers xsi:type="ecore:EClass" name="object_def" abstract="true" eSuperTypes="#//definables/function_def">
      <eStructuralFeatures xsi:type="ecore:EReference" name="init_process" upperBound="-1"
          eType="#//instructions/process_instruction" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="then_process" upperBound="-1"
          eType="#//instructions/process_instruction" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="physical_def" eSuperTypes="#//definables/object_def">
      <eStructuralFeatures xsi:type="ecore:EReference" name="specification" lowerBound="1"
          eType="#//definables/import_def"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="logical_def" eSuperTypes="#//definables/object_def"/>
    <eClassifiers xsi:type="ecore:EClass" name="variable_def" eSuperTypes="#//definition">
      <eTypeParameters name="T"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1"
          containment="true">
        <eGenericType eClassifier="#//instructions/process/variable_declaration">
          <eTypeArguments eTypeParameter="#//definables/variable_def/T"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="affectation" containment="true">
        <eGenericType eClassifier="#//expressions/expression">
          <eTypeArguments eTypeParameter="#//definables/variable_def/T"/>
        </eGenericType>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="parameters" nsURI="platform:/resource/Chips2BIP/Chips1.0.ecore/parameters"
      nsPrefix="chips.parameters">
    <eClassifiers xsi:type="ecore:EClass" name="int_param">
      <eGenericSuperTypes eClassifier="#//parameters/parameter">
        <eTypeArguments eClassifier="#//int"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="float_param">
      <eGenericSuperTypes eClassifier="#//parameters/parameter">
        <eTypeArguments eClassifier="#//float"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="bool_param">
      <eGenericSuperTypes eClassifier="#//parameters/parameter">
        <eTypeArguments eClassifier="#//bool"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="parameter" abstract="true">
      <eTypeParameters name="T"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eGenericSuperTypes eClassifier="#//input">
        <eTypeArguments eTypeParameter="#//parameters/parameter/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
